### ISSUE TITLE
Publicarlo en gh-pages

### ISSUE THREAD

**Issue by tzkmx** [eldagoquep/pokedex#1]
¿Podrías por favor publicar tu proyecto mediante github.io, para que pueda mostrarlo al Director?

Por cierto, también serviría para revisar un detalle de los modales, que el borde tapa las letras.

**Comment by eldagoquep** [comment]
OK @tzkmx , déjame y miro lo del github.io para que ya puedas mostrarlo. 

En cuanto a lo de los modales, gracias por hacerme ver eso, no me habia dado cuenta, voy a eso y te aviso en cuanto lo tenga.

**Comment by tzkmx** [comment]
Yo diría que al publicarlo, lo etiquetaras ya como versión 1.0 o algo así, para que quede constancia del commit en que resuelves esas cuestiones, antes de que hagas los cambios para una probable compatibilidad con la API de WordPress.
